
/* Drop Tables */

DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE TRAINER_RATE CASCADE CONSTRAINTS;
DROP TABLE T_CARE_LIKE CASCADE CONSTRAINTS;
DROP TABLE CARE CASCADE CONSTRAINTS;
DROP TABLE FOLLOW CASCADE CONSTRAINTS;
DROP TABLE N_COMMENT CASCADE CONSTRAINTS;
DROP TABLE N_LIKE CASCADE CONSTRAINTS;
DROP TABLE N_REPORT CASCADE CONSTRAINTS;
DROP TABLE NEIGHBOR CASCADE CONSTRAINTS;
DROP TABLE PET CASCADE CONSTRAINTS;
DROP TABLE P_COMMENT CASCADE CONSTRAINTS;
DROP TABLE P_LIKE CASCADE CONSTRAINTS;
DROP TABLE P_REPORT CASCADE CONSTRAINTS;
DROP TABLE PHOTO CASCADE CONSTRAINTS;
DROP TABLE R_REPORT CASCADE CONSTRAINTS;
DROP TABLE R_COMMENT CASCADE CONSTRAINTS;
DROP TABLE R_LIKE CASCADE CONSTRAINTS;
DROP TABLE RECOMMENDATION CASCADE CONSTRAINTS;
DROP TABLE T_LIKE CASCADE CONSTRAINTS;
DROP TABLE T_REPORT CASCADE CONSTRAINTS;
DROP TABLE TRAINER CASCADE CONSTRAINTS;
DROP TABLE DOG.MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CARE
(
	CARE_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	-- 신청이 완료되었는가 아닌가
	-- 디폴트 1 = 대기중
	-- 진행중  = 2
	-- 완료는 = 3 
	CARE_STATE number DEFAULT 1 NOT NULL,
	CARE_TITLE nvarchar2(100) NOT NULL,
	CARE_CONTENT nvarchar2(2000) NOT NULL,
	CARE_CLICKLINEL nvarchar2(1000) NOT NULL,
	CARE_CLICKLINEP nvarchar2(1000) NOT NULL,
	CARE_CLICKLINEA nvarchar2(100) NOT NULL,
	CARE_DATEPICKER nvarchar2(50) NOT NULL,
	CARE_TIMEPICKER nvarchar2(50) NOT NULL,
	CARE_PRICE nvarchar2(50) NOT NULL,
	CARE_IMAGES nvarchar2(1000) NOT NULL,
	CARE_LIKECOUNT number DEFAULT 0 NOT NULL,
	T_NO number,
	CARE_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CARE_NO)
);


CREATE TABLE CHAT
(
	CHAT_NO number NOT NULL,
	CARE_NO number NOT NULL,
	T_NO number NOT NULL,
	FROM_ID nvarchar2(2000) NOT NULL,
	CHAT_CONTENT nvarchar2(2000) NOT NULL,
	READ_ number DEFAULT 1 NOT NULL,
	CHAT_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CHAT_NO)
);


CREATE TABLE FOLLOW
(
	FOLLOW_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	FOLLOWING_ID varchar2(50) NOT NULL,
	PRIMARY KEY (FOLLOW_NO)
);


CREATE TABLE NEIGHBOR
(
	N_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	N_TITLE nvarchar2(100) NOT NULL,
	N_CONTENT nvarchar2(2000) NOT NULL,
	N_IMAGES nvarchar2(1000),
	N_COMMENTCOUNT number DEFAULT 0 NOT NULL,
	N_LIKECOUNT number DEFAULT 0 NOT NULL,
	N_REPORTCOUNT number DEFAULT 0 NOT NULL,
	N_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (N_NO)
);


CREATE TABLE N_COMMENT
(
	N_C_NO number NOT NULL,
	N_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	N_COMMENT nvarchar2(2000) NOT NULL,
	N_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (N_C_NO)
);


CREATE TABLE N_LIKE
(
	N_L_NO number NOT NULL,
	N_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	N_L_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (N_L_NO)
);


CREATE TABLE N_REPORT
(
	N_R_NO number NOT NULL,
	N_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	N_R_TITLE nvarchar2(100) NOT NULL,
	N_R_CONTENT nvarchar2(2000) NOT NULL,
	N_R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (N_R_NO)
);


CREATE TABLE PET
(
	PET_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	PET_GENDER varchar2(10) NOT NULL,
	PET_AGE number NOT NULL,
	PET_SPECIES nvarchar2(100) NOT NULL,
	PET_PROFILE nvarchar2(100) NOT NULL,
	PET_CONTENT nvarchar2(1000),
	PET_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (PET_NO)
);


CREATE TABLE PHOTO
(
	P_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	P_TITLE nvarchar2(100) NOT NULL,
	P_CONTENT nvarchar2(2000) NOT NULL,
	P_IMAGES nvarchar2(1000) NOT NULL,
	P_LIKECOUNT number DEFAULT 0 NOT NULL,
	P_COMMENTCOUNT number DEFAULT 0 NOT NULL,
	P_REPORTCOUNT number DEFAULT 0 NOT NULL,
	P_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (P_NO)
);


CREATE TABLE P_COMMENT
(
	P_C_NO number NOT NULL,
	P_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	P_COMMENT nvarchar2(2000) NOT NULL,
	P_C_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (P_C_NO)
);


CREATE TABLE P_LIKE
(
	P_L_NO number NOT NULL,
	P_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	P_L_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (P_L_NO)
);


CREATE TABLE P_REPORT
(
	P_R_NO number NOT NULL,
	P_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	P_R_TITLE nvarchar2(100) NOT NULL,
	P_R_CONTENT nvarchar2(2000) NOT NULL,
	P_R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (P_R_NO)
);


CREATE TABLE RECOMMENDATION
(
	R_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	R_TITLE nvarchar2(100) NOT NULL,
	R_CONTENT nvarchar2(2000) NOT NULL,
	R_IMAGES nvarchar2(1000),
	R_CLICKLINEL nvarchar2(1000) NOT NULL,
	R_CLICKLINEP nvarchar2(1000) NOT NULL,
	R_CLICKLINEA nvarchar2(100) NOT NULL,
	R_COMMENTCOUNT number DEFAULT 0 NOT NULL,
	R_LIKECOUNT number DEFAULT 0 NOT NULL,
	R_REPORTCOUNT number DEFAULT 0 NOT NULL,
	R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (R_NO)
);


CREATE TABLE R_COMMENT
(
	R_C_NO number NOT NULL,
	R_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	R_COMMENT nvarchar2(2000) NOT NULL,
	R_C_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (R_C_NO)
);


CREATE TABLE R_LIKE
(
	R_L_NO number NOT NULL,
	R_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	R_L_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (R_L_NO)
);


CREATE TABLE R_REPORT
(
	R_R_NO number NOT NULL,
	R_C_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	R_R_TITLE nvarchar2(100) NOT NULL,
	R_R_CONTENT nvarchar2(2000) NOT NULL,
	R_R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (R_R_NO)
);


CREATE TABLE TRAINER
(
	T_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	T_TITLE nvarchar2(100) NOT NULL,
	T_CONTENT nvarchar2(2000) NOT NULL,
	T_FILE nvarchar2(100),
	T_PHOTO nvarchar2(100),
	T_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (T_NO)
);


CREATE TABLE TRAINER_RATE
(
	T_R_NO number NOT NULL,
	T_NO number NOT NULL,
	CARE_NO number NOT NULL,
	TRAINER_RATE number NOT NULL,
	T_R_CONTENT nvarchar2(2000),
	T_R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (T_R_NO)
);


CREATE TABLE T_CARE_LIKE
(
	T_CARE_L_NO number NOT NULL,
	T_NO number NOT NULL,
	CARE_NO number NOT NULL,
	T_CARE_L_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (T_CARE_L_NO)
);


CREATE TABLE T_LIKE
(
	T_L_NO number NOT NULL,
	T_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	T_L_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (T_L_NO)
);


CREATE TABLE T_REPORT
(
	T_R_NO number NOT NULL,
	T_NO number NOT NULL,
	ID varchar2(50 char) NOT NULL,
	T_R_TITLE nvarchar2(100) NOT NULL,
	T_R_CONTENT nvarchar2(2000) NOT NULL,
	T_R_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (T_R_NO)
);


CREATE TABLE DOG.MEMBER
(
	ID varchar2(50 char) NOT NULL,
	PWD varchar2(50 char) NOT NULL,
	NICKNAME nvarchar2(20) NOT NULL UNIQUE,
	NAME varchar2(20 char) NOT NULL,
	GENDER varchar2(20 char) NOT NULL,
	ADDR nvarchar2(50) NOT NULL,
	ADDR2 nvarchar2(50) NOT NULL,
	BIRTH date NOT NULL,
	JOINDATE date DEFAULT SYSDATE NOT NULL,
	POSTCODE varchar2(20 char) NOT NULL,
	PIC_NAME nvarchar2(100),
	-- 일반 회원 = 1
	-- 돌보미 회원 = 2
	-- 관리자 = 3
	POWER number DEFAULT 1 NOT NULL,
	CONSTRAINT SYS_C007255 PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE CHAT
	ADD FOREIGN KEY (CARE_NO)
	REFERENCES CARE (CARE_NO)
;


ALTER TABLE TRAINER_RATE
	ADD FOREIGN KEY (CARE_NO)
	REFERENCES CARE (CARE_NO)
;


ALTER TABLE T_CARE_LIKE
	ADD FOREIGN KEY (CARE_NO)
	REFERENCES CARE (CARE_NO)
;


ALTER TABLE N_COMMENT
	ADD FOREIGN KEY (N_NO)
	REFERENCES NEIGHBOR (N_NO)
;


ALTER TABLE N_LIKE
	ADD FOREIGN KEY (N_NO)
	REFERENCES NEIGHBOR (N_NO)
;


ALTER TABLE N_REPORT
	ADD FOREIGN KEY (N_NO)
	REFERENCES NEIGHBOR (N_NO)
;


ALTER TABLE P_COMMENT
	ADD FOREIGN KEY (P_NO)
	REFERENCES PHOTO (P_NO)
;


ALTER TABLE P_LIKE
	ADD FOREIGN KEY (P_NO)
	REFERENCES PHOTO (P_NO)
;


ALTER TABLE P_REPORT
	ADD FOREIGN KEY (P_NO)
	REFERENCES PHOTO (P_NO)
;


ALTER TABLE R_COMMENT
	ADD FOREIGN KEY (R_NO)
	REFERENCES RECOMMENDATION (R_NO)
;


ALTER TABLE R_LIKE
	ADD FOREIGN KEY (R_NO)
	REFERENCES RECOMMENDATION (R_NO)
;


ALTER TABLE R_REPORT
	ADD FOREIGN KEY (R_C_NO)
	REFERENCES R_COMMENT (R_C_NO)
;


ALTER TABLE CHAT
	ADD FOREIGN KEY (T_NO)
	REFERENCES TRAINER (T_NO)
;


ALTER TABLE TRAINER_RATE
	ADD FOREIGN KEY (T_NO)
	REFERENCES TRAINER (T_NO)
;


ALTER TABLE T_CARE_LIKE
	ADD FOREIGN KEY (T_NO)
	REFERENCES TRAINER (T_NO)
;


ALTER TABLE T_LIKE
	ADD FOREIGN KEY (T_NO)
	REFERENCES TRAINER (T_NO)
;


ALTER TABLE T_REPORT
	ADD FOREIGN KEY (T_NO)
	REFERENCES TRAINER (T_NO)
;


ALTER TABLE CARE
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE FOLLOW
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE NEIGHBOR
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE N_COMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE N_LIKE
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE N_REPORT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE PET
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE PHOTO
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE P_COMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE P_LIKE
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE P_REPORT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE RECOMMENDATION
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE R_COMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE R_LIKE
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE R_REPORT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE TRAINER
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE T_LIKE
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;


ALTER TABLE T_REPORT
	ADD FOREIGN KEY (ID)
	REFERENCES DOG.MEMBER (ID)
;



/* Comments */

COMMENT ON COLUMN CARE.CARE_STATE IS '신청이 완료되었는가 아닌가
디폴트 1 = 대기중
진행중  = 2
완료는 = 3 ';
COMMENT ON COLUMN DOG.MEMBER.POWER IS '일반 회원 = 1
돌보미 회원 = 2
관리자 = 3';



